add txhash after submit transaction
SpaceLootNFT/spaceloot-webapp pull request #9
Opened 2021-09-14 10:34 UTC by apemon

- change interval period from 1 second to 5 second
- add check txharh after submit

2021-09-14 11:35 UTC, kaoths requested changes

2021-09-14 11:35 UTC, kaoths commented on src/views/home/pages/HomePage.tsx
> +>>>>>>> origin/main
These texts are from merge editor and would cause errors
**<<<<<<< HEAD**  
**=======**  
**>>>>>>> origin/main**

2021-09-14 11:35 UTC, kaoths commented on src/views/loot/LootBox.tsx
> +                </Link>
`Link` should have `a` as child  
see https://nextjs.org/docs/api-reference/next/link

2021-09-14 11:35 UTC, kaoths commented on src/views/common/BitButton.tsx
> +    box-shadow: inset (-4px * 1.5) (-4px * 1.5) 0px 0px #4aa52e;
value `(-4px)` cloud be treated as invalid by browsers, because it contains parentheses

`(-4px * 1.5)` --> use `rem` or `em` instead

apply to all occurrences in this file

2021-09-15 09:18 UTC, unnawut commented
Tests:
- [x] Send a spaceloot to another wallet (top of page, middle of page, end of page, start of list, end of list)
- [x] Send the same spaceloot back and forth

2021-09-15 10:02 UTC, merged